### PR TITLE
fixed formatting with autopep8

### PR DESCRIPTION
**Pull request by IonianTropics**

### CODE REVIEW

**Comment by ThomasTheSpaceFox** [comment]
No offense, but I don't agree with the whole 'indenting with spaces is better' point.

However, I probably _should_ create a code style guild for the project...

That said, I'm closing this PR for now, but don't be dissuaded from contributing. 

SBTCVM has no shortage of things on its todo lists...

**Comment by ThomasTheSpaceFox** [comment]
As an addendum, I honestly don't agree with PEP8 much at all... I'm not saying don't use it, you're welcome to using it on your own projects.
But pushing it in a pull rquest out of the blue, is kinda off-putting in my opinion.

**Comment by ThomasTheSpaceFox** [comment]
That said, thanks for inadvertently reminding me i need issue & pull request templates still, lol

**Comment by IonianTropics** [comment]
I should've added a heads up/or done a pull request on a fork. This was pretty unprofessional of me. I had to show someone how pull requests work for a research project that also had brought us to your repository. We've found this super helpful, and sorry for taking time out of your day.

**Pull request closed without merging**
