### PR TITLE
Added instructions to README.md

### PR DESCRIPTION
**Pull request by neauoire**
screen shot 2018-10-13 at 11 25 48 am

### CODE REVIEW

**Comment by ThomasTheSpaceFox** [comment]
First off, SBTCVM has TWO programming languages: SSTNPL and SBTCVM Assembly v3

Second, its 'VDI' shell, and its just a stub. no disk emulation whatsoever yet.

Third, help is to be placed in _textdocs_ Any user documentation there should be prefixed with 'help_' unless its in a subdirectory. you are welcome to start a getting-started guide there if you wish. Due note: SBTCVM is complex, and its documentation isn't complete yet, so not everything is there outside of the comments in the test programs in /ROMS/ yet...
```
Please see textdocs/help_gettingstarted.txt for a new user guide.
```
Forth, its SSTNPL (with 2 S's) the first standing for SBTCVM.

**Comment by ThomasTheSpaceFox** [comment]
I do appreciate your willingness to help though, don't get me wrong.

**Comment by ThomasTheSpaceFox** [comment]
I think ill write a guide.md in the main repository directory to settle this. I should have done similar a while ago anyways. :)

**Comment by neauoire** [comment]
That's alright, I just wanted to help.
There was broken markups and text that said to check the "manual" which is nowhere to be found, I figured it needed a bit of a revamp ;)

Anyways, this is a cool project, I'll keep watching how it evolves.

**Comment by ThomasTheSpaceFox** [comment]
yea, i decided 1 big manual wasn't going to cut it anymore so i removed that manual text. again something I should have done sooner. :D 

Thanks though, you reminded me to actually get to brushing the dust off the readme and adding a getting started guide. :)

And thank you, i think SBTCVM is a cool project too, though i might be a bit bias :)

**Comment by neauoire** [comment]
Thanks for adding the links to the readme 👍 It's perfect

**Pull request closed without merging**
